### ISSUE TITLE
Support type Union fields

### ISSUE THREAD

**Issue by s-knibbs** [s-knibbs/dataclasses-jsonschema#13]
Support type Unions fields by generating a json schema using [oneOf](https://json-schema.org/understanding-json-schema/reference/combining.html#oneof)

**Comment by uda** [comment]
The solution is good, but the fix does not take in account that the `is_optional` check is ruined when the type is `Union[str, None]`.
- Take in account that you need to add support for `Optional[str]` which is equivalent to `Union[str, None]`.
- The check `is_optional` should impact only the `required` boolean state, not the schema
- The function `is_optional` should be modified to test for both Optional and Union, and in the Union case check if `None in field.__args__` instead of the current check of the second value
