### ISSUE TITLE
Optional "types"

### ISSUE THREAD

**Issue by cgars** [s-knibbs/dataclasses-jsonschema#6]
Hey there. 
Thanks for this super useful projects. I've been using it a bit over the last few days and so far its been a smooth ride! 

I was wondering about Union type support or more precisely Optionals? 
I've seen you mentioned it as a todo in the Readme but I was wondering whether you are actively working on it? 
If not would you welcome a contribution there? And also would you have some starting remarks?
Thanks again for sharing your work! In any case i want to express our intrest in it!

Cheers

**Comment by s-knibbs** [comment]
I should probably make the documentation clearer but Optional is supported: see https://github.com/s-knibbs/dataclasses-jsonschema/blob/master/tests/conftest.py#L40.

I don't have any immediate plans to support type unions more generally since I'm only really using this Swagger/OpenAPI 2.0 which [doesn't support oneOf](https://stackoverflow.com/questions/36872277/oneof-in-swagger-schema-does-not-work).

I'm happy to accept a PR if you would like to add type union support however.
